spring:
  profiles:
    active: local
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DRIVER_CLASS}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: ${DB_PLATFORM}
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    show-sql: true

  # Mail
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: ${EMAIL_HOST}
    username: ${EMAIL_NAME}
    password: ${EMAIL_PASSWORD}

  main:
    allow-bean-definition-overriding: true

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

jwt:
  accessSecret: ${ACCESS_SECRET}
  refreshSecret: ${REFRESH_SECRET}
  time:
    accessExp: ${JWT_ACCESS_TIME}
    refreshExp: ${JWT_REFRESH_TIME}

