name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: ICEE-TEA Backend CI success Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          title: 🎉 ICEE-TEA Server CI success 🎉
          webhook: ${{ secrets.DISCORD_WEBHOOK_CI_BOT }}
          color: 00FF00

      - name: ICEE-TEA Backend CI failure Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          title: ❌ ICEE-TEA Server CI failed ❌
          webhook: ${{ secrets.DISCORD_WEBHOOK_CI_BOT }}
          color: FF0000
